Add support for attaching vlans to firewall interfaces
frankgreco/edge-sdk-go pull request #3
Opened 2022-10-15 15:57 UTC by de1ux

Noticed this in https://github.com/frankgreco/terraform-provider-edge: 

```
data "edge_interface_ethernet" "eth3_20" {
  id = "eth3.20"
}
```

where trying to attach a vlan to a firewall throws an error 

```
Could not unmarshal operation from data {"SET": {"error": {"interfaces ethernet eth3.20 firewall in name
│ main_firewall": "interface ethernet eth3.20: not a valid name\n\nValue validation failed\n"
```

Here's the network calls for attaching to a regular ethernet interface (**left**) vs. a vlan (**right**)

<img width="1131" alt="Screen Shot 2022-10-15 at 9 54 54 AM" src="https://user-images.githubusercontent.com/3915897/195995943-f2323e99-48ae-4dca-932c-a0728382e541.png">

I haven't tested this yet.

2022-10-15 16:02 UTC, frankgreco commented
Nice! I'll have time to review tomorrow!

2022-10-16 13:08 UTC, frankgreco commented
Thanks for another contribution! Overall it looks good. I left a minor nit in for `toEthernetMap` but everything else looked good. 

Looks like it's time for me to implement the creation of vlans!

> I haven't tested this yet.
I'd want to do a quick attach/update/detach test either using only the client or round trip with Terraform. I'm vacationing until the end of the week and my VPN isn't working unfortunately (to access my personal router) so if you need this in sooner and can show that flow working I'll be okay merging before then.

2022-10-16 13:08 UTC, frankgreco requested changes

2022-10-16 13:08 UTC, frankgreco commented on interfaces/ethernet/ethernet.go
> +	return ethernet
```suggestion
        // We can treat IDs like 'eth0.' as a non-virtual interfaces to gracefully handle null pointers.
	if parts := strings.Split(id, "."); len(parts) > 1 {
		ethID := parts[0]
		vlanID := parts[1]
		ethernet[ethID] = &types.Ethernet{
			Vif: map[string]*types.VirtualInterface{
				vlanID: {
					Firewall: firewall,
				},
			},
		}
	} else {
		ethernet[id] = &types.Ethernet{Firewall: firewall}
	}
	return ethernet
```

2022-10-16 13:08 UTC, frankgreco commented on interfaces/ethernet/ethernet.go
> +	return ethernet
There may be better ways to handle my suggested code but I think it should work. Could you add a quick test ensuring that an id like `eth0.` does indeed map to a non-virtual interface 🙏🏼

2022-10-16 13:23 UTC, frankgreco commented
```
data "edge_interface_ethernet" "eth3_20" {
  id = "eth3.20"
}
```

I think it's important to note that while this data source would work with this change, it's not likely to work in the future. This is because the data source implementation [does absolutely nothing](https://github.com/frankgreco/terraform-provider-edge/blob/master/internal/provider/data_interface_ethernet.go#L34) and purely just stores the inputed string.

The reason I say, "it's not likely to work in the future" is because `id = "eth3.20"` isn't the id for the ethernet interface but the vlan. Hence, I'd need to add something like 👇🏼 

```
data "edge_something_vlan" "eth3_20" {
  interface = "eth3"
  vlan_id = "20"

  id = "eth3.20" // or optionally this
}
```

Now all of this is outside the scope of this PR since it only touches attachment by ID.

2022-10-18 14:22 UTC, de1ux commented
thanks for the feedback, no rush whatsoever!

i did uncomment the go.mod `require` to link the two libs together, but got issues about incompatible terraform versions. do you have any notes on how to get these playing nicely, locally?

2022-11-07 02:33 UTC, closed without merging